const WhatsAppCallsFakeData = [
    {
        id: 1,
        name: 'Mark Doe',
        date: '12 jan',
        time: '11:14 am',
        video: false,
        image: 'https://bootdey.com/img/Content/avatar/avatar7.png',
        email: 'mark.doe@example.com',
        location: 'New York, USA',
        bio: 'Web Developer with over 5 years of experience in building responsive websites and applications. Passionate about technology and innovation, always looking for new challenges. Loves to share knowledge and mentor others in the field of software development.',
    },
    {
        id: 2,
        name: 'Clark Man',
        date: '12 jul',
        time: '15:58 am',
        video: false,
        image: 'https://bootdey.com/img/Content/avatar/avatar6.png',
        email: 'clark.man@example.com',
        location: 'Los Angeles, USA',
        bio: 'Graphic Designer and Artist who specializes in creating visually stunning designs for both print and digital media. With a keen eye for detail, I strive to bring ideas to life through creative solutions and innovative design techniques. Always exploring new trends in the industry.',
    },
    {
        id: 3,
        name: 'Jaden Boor',
        date: '12 aug',
        time: '12:45 am',
        video: true,
        image: 'https://bootdey.com/img/Content/avatar/avatar5.png',
        email: 'jaden.boor@example.com',
        location: 'Chicago, USA',
        bio: 'Music Producer and DJ with a passion for creating unique soundscapes that resonate with audiences. With experience in various genres, I focus on blending traditional and contemporary styles. I enjoy collaborating with other artists to push the boundaries of music production.',
    },
    {
        id: 4,
        name: 'Srick Tree',
        date: '12 feb',
        time: '08:32 am',
        video: false,
        image: 'https://bootdey.com/img/Content/avatar/avatar4.png',
        email: 'strick.tree@example.com',
        location: 'Miami, USA',
        bio: 'Fitness Trainer and Health Coach dedicated to helping clients achieve their health and wellness goals. With a background in nutrition and exercise science, I create personalized training plans that promote physical fitness and a balanced lifestyle. Passionate about motivating others.',
    },
    {
        id: 5,
        name: 'John Doe',
        date: '12 oct',
        time: '07:45 am',
        video: true,
        image: 'https://bootdey.com/img/Content/avatar/avatar3.png',
        email: 'john.doe@example.com',
        location: 'Seattle, USA',
        bio: 'Software Engineer and Blogger focused on building scalable applications and sharing insights through writing. I love exploring new technologies and frameworks while helping others understand complex concepts in software development. Avid reader and lifelong learner.',
    },
    {
        id: 6,
        name: 'John Doe',
        date: '12 jan',
        time: '09:54 am',
        video: false,
        image: 'https://bootdey.com/img/Content/avatar/avatar2.png',
        email: 'john.doe2@example.com',
        location: 'Austin, USA',
        bio: 'Photographer and Traveler who captures the beauty of the world through the lens. With a passion for storytelling, I use photography to convey emotions and experiences. Always on the lookout for the next adventure and new perspectives to share.',
    },
    {
        id: 8,
        name: 'John Doe',
        date: '12 jul',
        time: '11:22 am',
        video: true,
        image: 'https://bootdey.com/img/Content/avatar/avatar1.png',
        email: 'john.doe3@example.com',
        location: 'Boston, USA',
        bio: 'Culinary Artist and Chef specializing in fusion cuisine. I enjoy experimenting with flavors and techniques from different cultures to create unique dishes. Passionate about food sustainability and teaching others about the joys of cooking. Always seeking inspiration in the kitchen.',
    },
    {
        id: 9,
        name: 'John Doe',
        date: '12 aug',
        time: '13:33 am',
        video: false,
        image: 'https://bootdey.com/img/Content/avatar/avatar4.png',
        email: 'john.doe4@example.com',
        location: 'San Francisco, USA',
        bio: 'Entrepreneur and Business Consultant with a focus on helping startups grow and succeed. I leverage my experience in strategy and marketing to guide businesses through challenges and opportunities. Passionate about innovation and creating value in the marketplace.',
    },
    {
        id: 10,
        name: 'John Doe',
        date: '12 oct',
        time: '11:58 am',
        video: true,
        image: 'https://bootdey.com/img/Content/avatar/avatar7.png',
        email: 'john.doe5@example.com',
        location: 'Denver, USA',
        bio: 'Digital Marketer and Strategist experienced in crafting data-driven campaigns that drive engagement and conversions. I thrive on analyzing market trends and consumer behavior to create impactful marketing strategies. Passionate about continuous learning in the ever-evolving digital landscape.',
    },
    {
        id: 11,
        name: 'John Doe',
        date: '12 jan',
        time: '09:28 am',
        video: false,
        image: 'https://bootdey.com/img/Content/avatar/avatar1.png',
        email: 'john.doe6@example.com',
        location: 'Portland, USA',
        bio: 'Environmental Activist and Writer committed to raising awareness about sustainability and conservation. Through my writing, I aim to inspire action and promote a greener future. I believe in the power of community and collaboration to effect change.',
    },
    {
        id: 12,
        name: 'John Doe',
        date: '12 jan',
        time: '09:28 am',
        video: false,
        image: 'https://bootdey.com/img/Content/avatar/avatar1.png',
        email: 'john.doe7@example.com',
        location: 'Atlanta, USA',
        bio: 'Data Scientist and AI Enthusiast focused on leveraging data to solve complex problems and drive business decisions. I enjoy exploring machine learning techniques and sharing insights through workshops and talks. Passionate about using technology for social good.',
    },
    {
        id: 13,
        name: 'John Doe',
        date: '12 jan',
        time: '09:28 am',
        video: false,
        image: 'https://bootdey.com/img/Content/avatar/avatar1.png',
        email: 'john.doe8@example.com',
        location: 'Phoenix, USA',
        bio: 'Content Creator and Influencer dedicated to inspiring others through storytelling and engaging content. I share my experiences and insights on various platforms, aiming to build a community of like-minded individuals. Passionate about creativity and personal growth.',
    },
    {
        id: 14,
        name: 'John Doe',
        date: '12 jan',
        time: '09:28 am',
        video: false,
        image: 'https://bootdey.com/img/Content/avatar/avatar1.png',
        email: 'john.doe9@example.com',
        location: 'Dallas, USA',
        bio: 'Blockchain Developer and Tech Advocate with a strong interest in decentralized technologies. I work on building secure and scalable applications while promoting awareness of blockchain’s potential. Passionate about innovation and the future of technology.',
    },
];

export default WhatsAppCallsFakeData;
